const data = {
    products: [
        {
            _id: '1',
            name: 'almonds',
            category: 'vegetable',
            image: '/images/almonds.jpg',
            price: 120,
            countInStock: 10,
            brand: 'brand1',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality fresh product',
        },
        {
            _id: '2',
            name: 'apple',
            category: 'vegetable',
            image: '/images/apple.jpg',
            price: 100,
            countInStock: 10,
            brand: 'brand2',
            rating: 4.0,
            numReviews: 10,
            description: 'high quality fresh product',
        },
        {
            _id: '3',
            name: 'Lacoste banana',
            category: 'vegetable',
            image: '/images/banana.jpg',
            price: 220,
            countInStock: 10,
            brand: 'brand2',
            rating: 4.8,
            numReviews: 17,
            description: 'high quality fresh product',
        },
        {
            _id: '4',
            name: 'Lacoste beans',
            category: 'vegetable',
            image: '/images/beans.jpg',
            price: 78,
            countInStock: 10,
            brand: 'brand4',
            rating: 4.5,
            numReviews: 14,
            description: 'high quality fresh product',
        },
        {
            _id: '5',
            name: 'beetroot',
            category: 'vegetable',
            image: '/images/brinjal.jpg',
            price: 65,
            countInStock: 10,
            brand: 'brand5',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality fresh product',
        },
        {
            _id: '6',
            name: 'broccoli',
            category: 'vegetable',
            image: '/images/broccoli.jpg',
            price: 139,
            countInStock: 10,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 15,
            description: 'high quality fresh product',
        },
        {
            _id: '7',
            name: 'cashews',
            category: 'vegetable',
            image: '/images/cashews.jpg',
            price: 139,
            countInStock: 10,
            brand: 'brand6',
            rating: 4.5,
            numReviews: 15,
            description: 'high quality fresh product',
        },
        {
            _id: '8',
            name: 'broccoli',
            category: 'vegetable',
            image: '/images/corn.jpg',
            price: 139,
            countInStock: 0,
            brand: 'brand1',
            rating: 4.5,
            numReviews: 15,
            description: 'high quality fresh product',
        }
    ],
    };
export default data;